version: "3.9"

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  redis-commander:
      image: 'rediscommander/redis-commander:latest'
      environment:
        - REDIS_HOSTS=local:redis:6379
      ports:
        - '8081:8081'
      depends_on:
        - redis
        
  api:
    build: 
      dockerfile: Dockerfile
      context: .
    depends_on:
      - redis
      - postgres
    environment:
      WEBHOOK_HTTP: https://webhook.site/59737404-d918-4bbf-80d3-0614d8e47582
      DATABASE_URL: postgres://user:22042004@postgres:5432/banking
      NODE_ENV: prod
      PORT: 5000
    ports:
      - "4040:5000"


  postgres:
    image: postgres:12
    ports:
      - "35000:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 22042004
      POSTGRES_DB: banking

  pgadmin:
    image: dpage/pgadmin4:5.7
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 22042004
    ports:
      - "5050:80"
    depends_on:
      - postgres
